name: "Release new artifacts"

on:
  pull_request:
    branches:
      - "main"
  release:
    types:
      - created
      - released
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  REGISTRY: public.ecr.aws/b2h7a5c4/chaintable
  IMAGE: moonbeam-x
  DOCKERFILE: docker/moonbeam-tracing.Dockerfile

jobs:
  package:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            arch: amd64
          - runner: ubuntu-24.04-arm
            arch: arm64
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Runtime
        uses: actions/checkout@v4

      - name: Set env
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "REVISION=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Docker build and push
        run: |
          mkdir -p moonbase-substitutes-tracing
          cp wasm/moonbase-* moonbase-substitutes-tracing/
          mkdir -p moonriver-substitutes-tracing
          cp wasm/moonriver-* moonriver-substitutes-tracing/
          mkdir -p moonbeam-substitutes-tracing
          cp wasm/moonbeam-* moonbeam-substitutes-tracing/
          docker build -t ${REGISTRY}/${IMAGE}:${{ matrix.arch }}-${REVISION} -f ${DOCKERFILE} .
          docker push ${REGISTRY}/${IMAGE}:${{ matrix.arch }}-${REVISION}

  merge-docker-manifest:
    runs-on: ubuntu-latest
    needs: package
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Runtime
        uses: actions/checkout@v4

      - name: Set env
        run: |
          if [[ "${{ github.event_name }}" == "release" ]]; then
            echo "REVISION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          else
            echo "REVISION=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Merge manifest
        run: |
          docker buildx imagetools create --tag ${REGISTRY}/${IMAGE}:${REVISION} ${REGISTRY}/${IMAGE}:amd64-${REVISION} ${REGISTRY}/${IMAGE}:arm64-${REVISION}
