name: "Release new artifacts"

on:
  pull_request:
    branches:
      - "debank"
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  REGISTRY: public.ecr.aws/b2h7a5c4/chaintable
  IMAGE: moonbeam-tracing
  DOCKERFILE: docker/moonbeam-tracing.Dockerfile

jobs:
  package:
    strategy:
      matrix:
        arch: [amd64]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Checkout Runtime
        uses: actions/checkout@v4

      - name: Set env
        run: |
          echo "REVISION=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry-type: public

      - name: Docker build and push
        run: |
          mkdir -p moonbase-substitutes-tracing
          cp wasm/moonbase-* moonbase-substitutes-tracing/
          mkdir -p moonriver-substitutes-tracing
          cp wasm/moonriver-* moonriver-substitutes-tracing/
          mkdir -p moonbeam-substitutes-tracing
          cp wasm/moonbeam-* moonbeam-substitutes-tracing/
          docker build -t ${REGISTRY}/${IMAGE}:${{matrix.arch}}-${REVISION} -f ${DOCKERFILE} .
          docker push ${REGISTRY}/${IMAGE}:${{matrix.arch}}-${REVISION}
